### ISSUE TITLE
Confused about missing code and generating uncertain audio

### ISSUE THREAD

**Issue by ShawnPi233** [jishengpeng/ControlSpeech#1]
Thank you for your excellent work! But I found that the `datasets` in the `import from datasets load_metric` in the `wer.py` seems to be a local dependency, but I can't find it in the repository. In addition, when I use promptStyle to perform TTS inference on the style text Prompt, the generated audio is different each time. Why is this?

**Comment by jishengpeng** [comment]
> Thank you for your excellent work! But I found that the `datasets` in the `import from datasets load_metric` in the `wer.py` seems to be a local dependency, but I can't find it in the repository. In addition, when I use promptStyle to perform TTS inference on the style text Prompt, the generated audio is different each time. Why is this?

Hello, and thank you for your interest. The datasets library is a third-party library provided by HuggingFace, and the load_metric() function is a publicly accessible method. For more details, please refer to the [documentation](https://huggingface.co/docs/datasets/v1.0.1/loading_metrics.html). Additionally, it should be noted that the Promptstyle model incorporates stochastic elements during inference, such as the noise component in the duration predictor.

**Comment by ShawnPi233** [comment]
> > Thank you for your excellent work! But I found that the `datasets` in the `import from datasets load_metric` in the `wer.py` seems to be a local dependency, but I can't find it in the repository. In addition, when I use promptStyle to perform TTS inference on the style text Prompt, the generated audio is different each time. Why is this?
> 
> Hello, and thank you for your interest. The datasets library is a third-party library provided by HuggingFace, and the load_metric() function is a publicly accessible method. For more details, please refer to the [documentation](https://huggingface.co/docs/datasets/v1.0.1/loading_metrics.html). Additionally, it should be noted that the Promptstyle model incorporates stochastic elements during inference, such as the noise component in the duration predictor.

Thank you for your patience. After manually executing `pip install datasets`, the problem was solved. But I wonder if it would be better to add datasets to `requirements.txt`, because I couldn't find `datasets` in it, and an error occurred when installing dependencies, so I had to install dependencies manually. In short, thank you very much for your open-source code and answers, and I wish your paper will be successfully accepted!
