### ISSUE TITLE
请问可以提供crema-d数据集吗

### ISSUE THREAD

**Issue by Darcy0218** [jishengpeng/ControlSpeech#3]
您好，看您使用的数据还包含crema-d，但是Google drive链接里没有。请问可以提供下这个数据吗？

**Comment by jishengpeng** [comment]
> 您好，看您使用的数据还包含crema-d，但是Google drive链接里没有。请问可以提供下这个数据吗？


奥奥，我给的音频链接是原始textrolspeech中，我后面是更新了一版，我重新更新一下readme，感谢提醒

**Comment by Darcy0218** [comment]
大佬，请问你们git lfs是什么下的，我下的好慢，只有一秒10kb



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: jishengpeng ***@***.***&gt;
发送时间: 08/02/2024, 19:42
To: jishengpeng/ControlSpeech ***@***.***&gt;
抄送: Kevin Ng ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jishengpeng/ControlSpeech] 请问可以提供crema-d数据集吗 (Issue #3)

**Comment by jishengpeng** [comment]
> 大佬，请问你们git lfs是什么下的，我下的好慢，只有一秒10kb Sent&nbsp;from&nbsp;my&nbsp;iPhone
> […](#)
> ------------------ 原始邮件 ------------------ From: jishengpeng ***@***.***&gt; 发送时间: 08/02/2024, 19:42 To: jishengpeng/ControlSpeech ***@***.***&gt; 抄送: Kevin Ng ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [jishengpeng/ControlSpeech] 请问可以提供crema-d数据集吗 (Issue #3)

你的git lfs慢可能跟带宽/服务器代理/并发数相关。我已经重新将Crema-D数据集的链接换成了谷歌云盘。

**Comment by Darcy0218** [comment]
好的，非常感谢您



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: jishengpeng ***@***.***&gt;
发送时间: 08/03/2024, 00:09
To: jishengpeng/ControlSpeech ***@***.***&gt;
抄送: Kevin Ng ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jishengpeng/ControlSpeech] 请问可以提供crema-d数据集吗 (Issue #3)





  
大佬，请问你们git lfs是什么下的，我下的好慢，只有一秒10kb Sent&nbsp;from&nbsp;my&nbsp;iPhone
 …
 ------------------ 原始邮件 ------------------ From: jishengpeng @.&gt; 发送时间: 08/02/2024, 19:42 To: jishengpeng/ControlSpeech @.&gt; 抄送: Kevin Ng @.&gt;, Author @.&gt; Subject: Re: [jishengpeng/ControlSpeech] 请问可以提供crema-d数据集吗 (Issue #3)
  
你的git lfs慢可能跟带宽/服务器代理/并发数相关。我已经重新将Crema-D数据集的链接换成了谷歌云盘。
